version: '3'

services:
  redis:
    build:
      dockerfile: _redis.dockerfile
      context: ..
    networks:
      - cache
  driver_availability_ms:
    build:
      dockerfile: _app.dockerfile
      context: ..
    env_file:
      - .env
    ports:
      - 8050:8050
    depends_on:
      - redis
    networks:
      - cache
networks:
  cache:
